import {
  IsHexadecimal,
  IsNotEmpty,
  IsString,
  Matches,
  MinLength,
} from 'class-validator';

// DTO for `POST /auth/reset-password`.
export class ResetPasswordDto {
  // Password reset token generated by the backend.
  @IsString()
  @IsNotEmpty()
  @IsHexadecimal()
  token!: string;

  // Enforce a strong password policy.
  @IsString()
  @MinLength(8)
  @Matches(/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&]).+$/, {
    message:
      'Password must contain uppercase, lowercase, number, and special character',
  })
  password!: string;
}
