import { IsHexadecimal, IsNotEmpty, IsString } from 'class-validator';

// DTO for `GET /auth/verify`.
export class VerifyEmailDto {
  // Verification token generated by the backend.
  @IsString()
  @IsNotEmpty()
  @IsHexadecimal()
  token!: string;
}
